### ISSUE TITLE
Merged Pull Requests

### ISSUE THREAD

**Issue by SethMilliken** [mattr-/slate#23]
Issue descriptions in GitHub get autolinked cross-repository references. This may be a simpler way to keep track of changes from upstream.

jigish/slate#414
jigish/slate#395
jigish/slate#393
jigish/slate#387
jigish/slate#362
jigish/slate#351
jigish/slate#344
jigish/slate#371

**Comment by SethMilliken** [comment]
Cross-repo references in comments get nice summaries, too, so you could curate the comments on this issue to only include merged upstream requests to make it easier to see all the changes at a glance. 

jigish/slate#414
jigish/slate#395
jigish/slate#393
jigish/slate#387
jigish/slate#362
jigish/slate#351
jigish/slate#344
jigish/slate#371

**Comment by SethMilliken** [comment]
If you mention this issue `mattr-/slate#23` in the comments on the upstream pull requests you've merged, you'll get nice summaries of them listed here, too.

**Comment by mattr-** [comment]
Thanks for your contribution! While I dig GitHub's issue linking functionality for most things, I'm not interested in using here. The reason is that I want issues to indicate things I need to work on or need my attention vs. just being a collection of links to the "upstream" repository. The ultimate goal is to do releases once the issue count is low, preferably zero. 

Will GitHub's wikis will auto link issues for you? If so, I'd happily maintain a wiki page indicating what's been merged from upstream and what hasn't. I'll close this issue and the associated pull request, but I will see any comments you make on this issue. Thanks!
